//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unishare.Apps.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILanding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILanding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unishare.Apps.WindowsConfigurator.Resources.UILanding", typeof(UILanding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云名称.
        /// </summary>
        public static string CloudName {
            get {
                return ResourceManager.GetString("CloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建个人云.
        /// </summary>
        public static string CreateCloud {
            get {
                return ResourceManager.GetString("CreateCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建并将此设备加入新的个人云。.
        /// </summary>
        public static string CreateCloudHint {
            get {
                return ResourceManager.GetString("CreateCloudHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备名称.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出向导.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邀请码.
        /// </summary>
        public static string Invitation {
            get {
                return ResourceManager.GetString("Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入已有个人云.
        /// </summary>
        public static string JoinCloud {
            get {
                return ResourceManager.GetString("JoinCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加入其它设备创建的个人云。.
        /// </summary>
        public static string JoinCloudHint {
            get {
                return ResourceManager.GetString("JoinCloudHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人云.
        /// </summary>
        public static string PersonalCloud {
            get {
                return ResourceManager.GetString("PersonalCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 欢迎使用个人云.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您的设备目前没有加入个人云，您可以…….
        /// </summary>
        public static string WelcomeHint {
            get {
                return ResourceManager.GetString("WelcomeHint", resourceCulture);
            }
        }
    }
}
