//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPersonalCloud.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UILanding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILanding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSPersonalCloud.WindowsConfigurator.Resources.UILanding", typeof(UILanding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Name.
        /// </summary>
        public static string CloudName {
            get {
                return ResourceManager.GetString("CloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PERSONAL CLOUD.
        /// </summary>
        public static string CreateCloud {
            get {
                return ResourceManager.GetString("CreateCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string CreateCloudHint {
            get {
                return ResourceManager.GetString("CreateCloudHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Create Personal Cloud.
        /// </summary>
        public static string ErrorCreatingCloud {
            get {
                return ResourceManager.GetString("ErrorCreatingCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Enroll This Device.
        /// </summary>
        public static string ErrorEnrollingDevice {
            get {
                return ResourceManager.GetString("ErrorEnrollingDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation Code.
        /// </summary>
        public static string Invitation {
            get {
                return ResourceManager.GetString("Invitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN BY INVITATION.
        /// </summary>
        public static string JoinCloud {
            get {
                return ResourceManager.GetString("JoinCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN.
        /// </summary>
        public static string JoinCloudHint {
            get {
                return ResourceManager.GetString("JoinCloudHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Cloud.
        /// </summary>
        public static string PersonalCloud {
            get {
                return ResourceManager.GetString("PersonalCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Your Personal Cloud.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
