//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unishare.Apps.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UISettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UISettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unishare.Apps.WindowsConfigurator.Resources.UISettings", typeof(UISettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备名称无效.
        /// </summary>
        public static string AlertInvalidDeviceName {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请使用简短的名称，尽量不与其它设备重复，且尽量不包含特殊字符。.
        /// </summary>
        public static string AlertInvalidDeviceNameMessage {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人云.
        /// </summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设备名称.
        /// </summary>
        public static string CloudDeviceName {
            get {
                return ResourceManager.GetString("CloudDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无法生成个人云邀请码.
        /// </summary>
        public static string CloudInviteError {
            get {
                return ResourceManager.GetString("CloudInviteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 通过邀请码将其它设备加入个人云.
        /// </summary>
        public static string CloudInviteNone {
            get {
                return ResourceManager.GetString("CloudInviteNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成邀请码.
        /// </summary>
        public static string CloudInviteStart {
            get {
                return ResourceManager.GetString("CloudInviteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止邀请.
        /// </summary>
        public static string CloudInviteStop {
            get {
                return ResourceManager.GetString("CloudInviteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出 / 切换个人云.
        /// </summary>
        public static string CloudLeave {
            get {
                return ResourceManager.GetString("CloudLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 云名称.
        /// </summary>
        public static string CloudName {
            get {
                return ResourceManager.GetString("CloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存更改.
        /// </summary>
        public static string CloudSaveChanges {
            get {
                return ResourceManager.GetString("CloudSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 个人云控制台.
        /// </summary>
        public static string Configurator {
            get {
                return ResourceManager.GetString("Configurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出控制台.
        /// </summary>
        public static string DeveloperExit {
            get {
                return ResourceManager.GetString("DeveloperExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新启动服务.
        /// </summary>
        public static string DeveloperRestartService {
            get {
                return ResourceManager.GetString("DeveloperRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件管理器插件.
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 将个人云显示为网络驱动器.
        /// </summary>
        public static string ExplorerMasterSwitch {
            get {
                return ResourceManager.GetString("ExplorerMasterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盘符.
        /// </summary>
        public static string ExplorerMountPoint {
            get {
                return ResourceManager.GetString("ExplorerMountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件共享.
        /// </summary>
        public static string FileSharing {
            get {
                return ResourceManager.GetString("FileSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许此设备分享文件.
        /// </summary>
        public static string FileSharingMasterSwitch {
            get {
                return ResourceManager.GetString("FileSharingMasterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享文件夹.
        /// </summary>
        public static string FileSharingPath {
            get {
                return ResourceManager.GetString("FileSharingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重新选择.
        /// </summary>
        public static string FileSharingPathSelect {
            get {
                return ResourceManager.GetString("FileSharingPathSelect", resourceCulture);
            }
        }
    }
}
