//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSPersonalCloud.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UISettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UISettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NSPersonalCloud.WindowsConfigurator.Resources.UISettings", typeof(UISettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot generate invitation..
        /// </summary>
        public static string AlertCannotGenerateInvite {
            get {
                return ResourceManager.GetString("AlertCannotGenerateInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot mount network drive.
        /// </summary>
        public static string AlertCannotMountDrive {
            get {
                return ResourceManager.GetString("AlertCannotMountDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cloud mounted network drive disconnected unexpectedly. There was another program interfering with our file system driver or the driver was not installed.
        ///
        ///If you continue seeing this dialog, uncheck the &quot;Mount as Network Drive&quot; box to avoid it for the moment. Contact your system administrator or reinstall Personal Cloud to resolve this issue..
        /// </summary>
        public static string AlertCannotMountDriveTroubleshoot {
            get {
                return ResourceManager.GetString("AlertCannotMountDriveTroubleshoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid device name. Use a name that is short, is unique, and does not contain special characters..
        /// </summary>
        public static string AlertInvalidDeviceName {
            get {
                return ResourceManager.GetString("AlertInvalidDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOK {
            get {
                return ResourceManager.GetString("AlertOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cloud.
        /// </summary>
        public static string Cloud {
            get {
                return ResourceManager.GetString("Cloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string CloudDeviceName {
            get {
                return ResourceManager.GetString("CloudDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite other devices.
        /// </summary>
        public static string CloudInviteStart {
            get {
                return ResourceManager.GetString("CloudInviteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string CloudInviteStop {
            get {
                return ResourceManager.GetString("CloudInviteStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Personal cloud.
        /// </summary>
        public static string CloudLeave {
            get {
                return ResourceManager.GetString("CloudLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud name.
        /// </summary>
        public static string CloudName {
            get {
                return ResourceManager.GetString("CloudName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CloudSaveChanges {
            get {
                return ResourceManager.GetString("CloudSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Cloud.
        /// </summary>
        public static string Configurator {
            get {
                return ResourceManager.GetString("Configurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string DeveloperExit {
            get {
                return ResourceManager.GetString("DeveloperExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string DeveloperOptions {
            get {
                return ResourceManager.GetString("DeveloperOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart service.
        /// </summary>
        public static string DeveloperRestartService {
            get {
                return ResourceManager.GetString("DeveloperRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop service.
        /// </summary>
        public static string DeveloperStopService {
            get {
                return ResourceManager.GetString("DeveloperStopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows service.
        /// </summary>
        public static string DeveloperWindowsService {
            get {
                return ResourceManager.GetString("DeveloperWindowsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File explorer integration.
        /// </summary>
        public static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mount Personal cloud as network drive.
        /// </summary>
        public static string ExplorerMasterSwitch {
            get {
                return ResourceManager.GetString("ExplorerMasterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive letter.
        /// </summary>
        public static string ExplorerMountPoint {
            get {
                return ResourceManager.GetString("ExplorerMountPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File sharing.
        /// </summary>
        public static string FileSharing {
            get {
                return ResourceManager.GetString("FileSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow file sharing on this device.
        /// </summary>
        public static string FileSharingMasterSwitch {
            get {
                return ResourceManager.GetString("FileSharingMasterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this folder.
        /// </summary>
        public static string FileSharingPath {
            get {
                return ResourceManager.GetString("FileSharingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string FileSharingPathSelect {
            get {
                return ResourceManager.GetString("FileSharingPathSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the following code on other devices.
        ///
        ///Closing this dialog stop inviting..
        /// </summary>
        public static string InvitesSentMessage {
            get {
                return ResourceManager.GetString("InvitesSentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations sent.
        /// </summary>
        public static string InvitesSentTitle {
            get {
                return ResourceManager.GetString("InvitesSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh devices.
        /// </summary>
        public static string RefreshNetwork {
            get {
                return ResourceManager.GetString("RefreshNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurator not ready.
        /// </summary>
        public static string ServiceNotRunning {
            get {
                return ResourceManager.GetString("ServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes to device profile are saved..
        /// </summary>
        public static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop service.
        /// </summary>
        public static string StopService {
            get {
                return ResourceManager.GetString("StopService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop inviting.
        /// </summary>
        public static string StopVerification {
            get {
                return ResourceManager.GetString("StopVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cloud and its components are initializing. Please wait for a few minutes and try again.
        ///
        ///If you continue to receive this error after a few minutes, use &quot;Windows Service&quot; &gt; &quot;Restart Service&quot; in the right-click menu to restart companion service..
        /// </summary>
        public static string WaitForService {
            get {
                return ResourceManager.GetString("WaitForService", resourceCulture);
            }
        }
    }
}
