//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unishare.Apps.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStorage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStorage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unishare.Apps.WindowsConfigurator.Resources.UIStorage", typeof(UIStorage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key ID.
        /// </summary>
        public static string AliYunAccessID {
            get {
                return ResourceManager.GetString("AliYunAccessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Key Secret.
        /// </summary>
        public static string AliYunAccessKey {
            get {
                return ResourceManager.GetString("AliYunAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket.
        /// </summary>
        public static string AliYunBucket {
            get {
                return ResourceManager.GetString("AliYunBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string AliYunConnectionName {
            get {
                return ResourceManager.GetString("AliYunConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint.
        /// </summary>
        public static string AliYunEndpoint {
            get {
                return ResourceManager.GetString("AliYunEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        public static string AzureAccountName {
            get {
                return ResourceManager.GetString("AzureAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob Container.
        /// </summary>
        public static string AzureContainer {
            get {
                return ResourceManager.GetString("AzureContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URI / Suffix.
        /// </summary>
        public static string AzureEndpoint {
            get {
                return ResourceManager.GetString("AzureEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Key or SAS.
        /// </summary>
        public static string AzureKey {
            get {
                return ResourceManager.GetString("AzureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Use This Name.
        /// </summary>
        public static string ConnectionBadName {
            get {
                return ResourceManager.GetString("ConnectionBadName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to Online Storage.
        /// </summary>
        public static string ConnectToStorage {
            get {
                return ResourceManager.GetString("ConnectToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to Verify Credentials.
        /// </summary>
        public static string ErrorAuthenticating {
            get {
                return ResourceManager.GetString("ErrorAuthenticating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alibaba Cloud did not accept these credentials..
        /// </summary>
        public static string ErrorAuthenticatingAliYun {
            get {
                return ResourceManager.GetString("ErrorAuthenticatingAliYun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Blob Storage did not accept these credentials..
        /// </summary>
        public static string ErrorAuthenticatingAzure {
            get {
                return ResourceManager.GetString("ErrorAuthenticatingAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Online Storage.
        /// </summary>
        public static string ManageConnections {
            get {
                return ResourceManager.GetString("ManageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alibaba Cloud.
        /// </summary>
        public static string ProviderAliYun {
            get {
                return ResourceManager.GetString("ProviderAliYun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Blob Storage.
        /// </summary>
        public static string ProviderAzure {
            get {
                return ResourceManager.GetString("ProviderAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Connections.
        /// </summary>
        public static string SavedStorageConnections {
            get {
                return ResourceManager.GetString("SavedStorageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share credentials with other devices.
        /// </summary>
        public static string SaveToCloud {
            get {
                return ResourceManager.GetString("SaveToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage.
        /// </summary>
        public static string StorageProvider {
            get {
                return ResourceManager.GetString("StorageProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Services.
        /// </summary>
        public static string StorageServices {
            get {
                return ResourceManager.GetString("StorageServices", resourceCulture);
            }
        }
    }
}
