//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unishare.Apps.WindowsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStorage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStorage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unishare.Apps.WindowsConfigurator.Resources.UIStorage", typeof(UIStorage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户 ID.
        /// </summary>
        public static string AliYunAccessID {
            get {
                return ResourceManager.GetString("AliYunAccessID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问密钥.
        /// </summary>
        public static string AliYunAccessKey {
            get {
                return ResourceManager.GetString("AliYunAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储空间.
        /// </summary>
        public static string AliYunBucket {
            get {
                return ResourceManager.GetString("AliYunBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 服务名称.
        /// </summary>
        public static string AliYunConnectionName {
            get {
                return ResourceManager.GetString("AliYunConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 域名.
        /// </summary>
        public static string AliYunEndpoint {
            get {
                return ResourceManager.GetString("AliYunEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加第三方服务.
        /// </summary>
        public static string ConnectToStorage {
            get {
                return ResourceManager.GetString("ConnectToStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置第三方服务.
        /// </summary>
        public static string ManageConnections {
            get {
                return ResourceManager.GetString("ManageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 阿里云.
        /// </summary>
        public static string ProviderAliYun {
            get {
                return ResourceManager.GetString("ProviderAliYun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string SaveAndClose {
            get {
                return ResourceManager.GetString("SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已保存的凭据.
        /// </summary>
        public static string SavedStorageConnections {
            get {
                return ResourceManager.GetString("SavedStorageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 存储提供商.
        /// </summary>
        public static string StorageProvider {
            get {
                return ResourceManager.GetString("StorageProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在线存储服务.
        /// </summary>
        public static string StorageServices {
            get {
                return ResourceManager.GetString("StorageServices", resourceCulture);
            }
        }
    }
}
